name: vantage_ai
description: "Navigation assistant for visually impaired users."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  camera: ^0.10.5+9
  tflite_flutter: ^0.10.4
  image: ^4.1.7
  flutter_tts: ^3.8.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/vantage.tflite
